project:
  type: website

website:
  title: "De Begaafden Wijzer"
  favicon: /www/images/bw_logo.png
  search:
    location: navbar
    type: overlay
  navbar:
    logo: /www/images/bw_logo.png
    toggle-position: right
    right:
      - text: "Home"
        href: index.qmd
      - text: "Begaaden wijzer"
        menu:
          - text: Begaafden wijzer
            file: content/begaafden_wijzer/index.qmd
          - text: "Visie"
            file: content/begaafden_wijzer/visie.qmd
          - text: "Activiteiten"
            file: content/begaafden_wijzer/activiteiten.qmd
          - text: "Tarieven"
            file: content/begaafden_wijzer/tarieven.qmd
      - text: "Hoogbegaafdheid"
        file: content/hoogbegaafdheid/index.qmd
        menu:
          - text: "Kenmerken"
            file: content/hoogbegaafdheid/kenmerken.qmd
          - text: "Onderwijs"
            file: content/hoogbegaafdheid/onderwijs_aanpassing.qmd
      - text: "Ouders en Kinderen"
        file: content/ouders_en_kinderen/index.qmd
        menu:
          - text: "Kenmerken"
            file: content/ouders_en_kinderen/kindbegeleiding.qmd
          - text: "Onderwijs"
            file: content/ouders_en_kinderen/ouderbegeleilding.qmd
      - text: "Contact"
        file: content/contact/index.qmd
  page-navigation: true
  back-to-top-navigation: false

  page-footer:
    left: >-
      [![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT) [![CC BY 4.0](https://img.shields.io/badge/License-CC%20BY%204.0-lightgrey.svg)](http://creativecommons.org/licenses/by/4.0/) 
      © 2024, Begaafden Wijzer
    right:
      - icon: house
        href: https://daniellekotter.github.io/website-dani
      - icon: envelope
        href: mailto:debegaafdenwijzer@ziggo.nl
      - icon: linkedin
        href: https://www.linkedin.com/in/marijke-schekkerman-b6424917

language: 
  search-text-placeholder: Search

format:
  html:
    theme: [flatly, theme.scss]
    css:
      - styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute:
  freeze: auto
