project:
  type: website
  output-dir: docs

website:
  title: De Begaafden Wijzer
  favicon: /www/logos/bw_logo.png
  search:
    location: navbar
    type: overlay
  sidebar: false
  navbar:
    title: false
    logo: /www/logos/logo4.png
    logo-href: /content/index.qmd
    toggle-position: right
    right:
      - text: "Home"
        href: content/index.qmd
      - text: "De Begaafden Wijzer"
        menu:
          - text: Visie
            file: content/begaafden_wijzer/index.qmd
          - text: "Doelgroepen"
            file: content/begaafden_wijzer/doelgroepen.qmd
          - text: "Activiteiten"
            file: content/begaafden_wijzer/activiteiten.qmd
          - text: "Tarieven"
            file: content/begaafden_wijzer/tarieven.qmd
      - text: "Hoogbegaafdheid"
        menu:
          - text: "Overzicht"
            file: content/hoogbegaafdheid/index.qmd
          - text: "Kenmerken"
            file: content/hoogbegaafdheid/kenmerken.qmd
          - text: "Onderwijs"
            file: content/hoogbegaafdheid/onderwijs_aanpassing.qmd
      - text: "Ouders en Kinderen"
        menu:
          - text: "Overzicht"
            file: content/ouders_en_kinderen/index.qmd
          - text: "Kindbegeleiding"
            file: content/ouders_en_kinderen/kindbegeleiding.qmd
          - text: "Ouderbegeleiding"
            file: content/ouders_en_kinderen/ouderbegeleiding.qmd
      - text: "Projecten"
        href: projecten/index.qmd
      - text: "Contact"
        file: content/contact/index.qmd
  page-navigation: true
  back-to-top-navigation: false

  page-footer:
    left:
      - text: Algemene Voorwaarden
        file: /www/Algemene-voorwaarden-De-Begaafden-Wijzer-2018.pdf
        target: _blank
    right:
      - icon: house
        href: https://debegaadenwijzer.nl
      - icon: envelope
        href: mailto:debegaafdenwijzer@ziggo.nl
      - icon: linkedin
        href: https://www.linkedin.com/in/marijke-schekkerman-b6424917

language:
  search-text-placeholder: Search

format:
  html:
    highlight-style: github-dark # changes text from code chunks to white 
    smooth-scroll: true
    theme: [flatly, www/theme.scss]
    toc: true
    code-link: true
    link-external-newwindow: true 

execute:
  freeze: auto
