---
title: "Maatwerk voor scholen"
---

In overleg met de individuele scholen is het mogelijk om een maatwerktraject uit te werken en uit te zetten. De school inventariseert de stand van zaken ( bijvoorbeeld met behulp van de [digitale checklist PO](%22http://talentstimuleren.nl/onderwijs/primair-onderwijs/po-beleid/checklist-begaafdenwijzer-po%22)) en op basis van de situatie en de wensen van de school wordt een maatwerktraject afgesproken. Zaken als teambijeenkomsten, ondersteuning van de werkgroep leden of het ondersteunen van een IB-er bij het signaleren kunnen onderdelen worden van dit traject. Het uitgangspunt bij maatwerktrajecten is dat het gaat om het professionaliseren van de leerkrachten  en de IB-er of coördinator Begaafdheid en Talentontwikkeling, op de werkvloer.

Dergelijke trajecten hebben al bij veel scholen geleid tot onderwijsaanpassingen voor meer- en hoogbegaafde kinderen en het professionaliseren van het team en het scholen van de specialisten HB op des betreffende scholen.

### Professionalisering door Workshops op thema:

Voor kleinere thema’s is het ook mogelijk om professionalisering in de vorm van een Workshop te regelen, te denken valt dan aan:

-   Signaleren met de Profielen van Betts & Neihart
-   Verrijking in de kleuterklassen
-   Fixed en groei mindset, de basis van een open leerhouding
-   Strategieën trainen met denk- en redeneerspellen
-   Het verrijken van de rekenlessen
-   Het verrijken van de taallessen
-   Opzetten van een plusklas aanbod
-   Onderzoeken en Ontwerpen leren in de zaakvakken
