---
title: "Visie"
---

"De Begaafden Wijzer" heeft als doel ouders en scholen te helpen bij het ontwikkeling en begeleiden van (hoog)begaafde leerlingen.

1. **Het eerste uitgangspunt** is het (hoog)begaafde kind zelf; wat zijn zijn/haar mogelijkheden, zijn/haar interesses en waar loopt hij/zij in het leven tegenaan.

2. **Het tweede uitgangspunt** is de school; wat vindt de school belangrijk en welke mogelijkheden zijn er binnen de school.

3. **Het derde uitgangspunt** is de omgeving van de leerling thuis, ouders en vrienden, welke mogelijkheden zijn daar om de leerling een goede ontwikkeling te geven.
Pas als deze drie op elkaar zijn afgestemd krijgt een (hoog)intelligent kind een kans om een (hoog)begaafde leerling te worden.

De opdrachtgevers van ‘De Begaafden Wijzer’ bestaan zowel uit individuele ouders als uit scholen, gemeenten en stichtingsbesturen, tevens is er een breed netwerk met andere instellingen en zorgverleners op het gebied van de begeleiding van (hoog)begaafde leerlingen.

De Begaafden Wijzer richt zich op (hoog)begaafden van alle leeftijden, dus zowel op de voorschoolse periode (0-4 jaar), de basisschool (4-12 jaar) als het voorgezet onderwijs (12 +) en de periode erna.
