---
title: "(Hoog)begaafden in de klas ?? ……. en nu ??"
---

Een (hoog)begaafde leerling is niet altijd de zelfstandige leerling, die meedoet met de klas en hoge cijfers haalt, daarnaast op schaken zit, een muziekinstrument bespeelt, in teamverband een sport doet en daarnaast nog alle dagen tijd vindt om boeken te lezen. 

(Hoog)begaafde volwassenen worden als (hoog)intelligent kind geboren, maar de ontwikkeling tot (hoog)begaafde leerling is afhankelijk van de mate waarin de leerling wordt gestimuleerd in zijn creativiteit en motivatie. 
De (hoog)begaafde leerling heeft extra uitdaging nodig om te zorgen dat hij/zij zich niet gaat vervelen op school. Want bij verveling ontstaat gedrag als lekker wegdromen in de les, lage cijfers halen of juist de les verstoren door storend gedrag, gepest worden of juist gaan pesten, faalangst krijgen, waardoor moeilijke opdrachten worden vermeden.

Doordat intelligentieniveau en belangstelling afwijken van de groep met leeftijdgenoten, voelt de leerling zich snel een buitenstaander. De leerling wordt niet begrepen.

De (hoog)begaafde leerling heeft samenwerking met ontwikkelingsgelijken nodig om te zorgen dat hij/zij een juist zelfbeeld kan ontwikkelen en om te zorgen dat hij/zij misschien wel anders is, maar dat hij/zij daarin niet alleen staat.

Door goede signalering, onderwijsaanpassing en begeleiding is veelal te voorkomen dat  leerlingen gaan onderpresteren, faalangst ontwikkelen of niet leren zich voor schoolse taken in te zetten, waardoor de leerling een evenwichtige ontwikkeling kan doormaken.
