---
title: "Onderwijs"
---

Binnen het onderwijs is de laatste jaren steeds meer belangstelling voor deze doelgroep. Werden de afgelopen jaren juist de kinderen aan de onderkant extra ondersteund, is het nu de groep aan de bovenkant waarmee de scholen meer aan het werk willen. Op diverse scholen is het onderwijs inmiddels aangepast of is het team er mee bezig. In diverse plaatsten is er een Leonardoschool gestart, alleen voor hoogbegaafde leerlingen met een eigen concept. Van belang binnen het onderwijs is dat de leerlingen worden gezien, gesignaleerd en dat er dan op een gestructureerde wijze de leerling op een aangepast niveau onderwijs kan genieten. Hierdoor is een gezonde doorgroei naar het volgende type onderwijs en tot een evenwichtige (hoog)begaafde volwassene beter gewaarborgd.

De (hoog)begaafde leerling heeft extra uitdaging nodig om te zorgen dat hij/zij zich niet gaat vervelen op school. Want bij verveling ontstaat gedrag als lekker wegdromen in de les, lage cijfers halen of juist de les verstoren door storend gedrag, gepest worden of juist gaan pesten, faalangst krijgen, waardoor moeilijke opdrachten worden vermeden.

Doordat intelligentieniveau en belangstelling afwijken van de groep met leeftijdgenoten, voelt de leerling zich snel een buitenstaander. De leerling wordt niet begrepen.

De (hoog)begaafde leerling heeft samenwerking met ontwikkelingsgelijken nodig om te zorgen dat hij/zij een juist zelfbeeld kan ontwikkelen en om te zorgen dat hij/zij misschien wel anders is, maar dat hij/zij daarin niet alleen staat.

Door goede signalering, onderwijsaanpassing en begeleiding is veelal te voorkomen dat leerlingen gaan onderpresteren, faalangst ontwikkelen of niet leren zich voor schoolse taken in te zetten, waardoor de leerling een evenwichtige ontwikkeling kan doormaken.

Veel scholen bieden nu een programma aan voor de gemiddelde leerling. RT (Remedial Teaching) is beschikbaar voor de leerlingen die moeite hebben met lezen, rekenen of taal. Aanpassing voor de kinderen die snel klaar zijn, bestaat veelal uit een map met werkbladen met het zelfde niveau onderwijsaanbod.

### Onderwijsaanpassingen / Compacten

De meeste (hoog)begaafde leerlingen maken grote leerstappen of beheersen de stof op groepsniveau al doordat ze zich zelf dingen aan leren.

Voor de hele groep begaafde leerlingen is de eerste stap van onderwijs aanpassing het compacten van de lesstof. De leerling hoeft minder oefenopdrachten te maken, omdat de leerling met enkele oefeningen de materie al beheerst. Compacten kan bij alle vakken worden uitgevoerd, laat de extra oefensommen weg en zorg dat ze op hun eigen manier, met grote stappen door de stof heen gaan. Er zijn diverse methoden waarmee de leerkracht wordt geholpen de stof in te dikken. Door het compacten is de leerling veel eerder klaar dan de leerlingen die alle sommen moeten maken, die tijd kan worden ingevuld met werk op een ander niveau waardoor de (hoog) begaafde leerling zich uitgedaagd voelt: verrijken of verdiepen.

### Onderwijsaanpassingen / Verrijken of verbreden

Bij het verrijken wordt gebruik gemaakt van materiaal van het zelfde vak waarin op een ander abstractie niveau inspanning van de leerling wordt verwacht. Goed verrijkingsmateriaal is niet meer van het zelfde, maar anders!

Bij verbreden worden andere vakken aangeboden dan in het normale lesprogramma zitten, bijvoorbeeld sterrenkunde, schaken of Spaans. Van belang is bij de keuze is om niet vooruit te lopen op hogere jaren of het voortgezet onderwijs.

De markt heeft ondertussen op de doelgroep ingespeeld en er bestaan nu diverse methoden en lespakketten gericht op de (hoog)begaafde leerling. De inzet van dit materiaal moet echter wel goed en overdacht ingevoerd worden. Als het werk “extra” naast het groepswerk wordt aangeboden, heeft de leerling al snel het gevoel dat het een soort straf is en is de leerling minder geneigd om het extra werk te doen. Bovendien is de leerling niet gewend om opdrachten te moeten doen waarbij de leerling zich moet inzetten, want het groepswerk is altijd zo makkelijk en zo klaar.

### Onderwijsaanpassingen / Verrijkingsklas

Voor de ontwikkeling en het zelfbeeld van de hoogbegaafde leerlingen is het goed om zo nu en dan samen te kunnen werken met andere leerlingen die beschikken over dezelfde (leer)eigenschappen. Er kan dan juist aan andere vakken gewerkt worden en op een manier waarbij de leerlingen zelf veel meer moeten nadenken en bedenken hoe ze dingen (willen) aanpakken. Dit is in de klas moeilijk te realiseren, vanwege de organisatie en vanwege het gering aantal kinderen. Binnen een school of overkoepelend kan er een plusklas of verrijkingsklas worden opgezet waarin deze werkwijze wel kan worden uitgevoerd. Een plek waar de (hoog)begaafde leerling zich zelf kan zijn onder ontwikkelingsgelijken en zijn of haar talenten verder kan gebruiken.

### Onderwijsaanpassingen / Versnellen

Het kan voorkomen dat een (hoog)begaafde leerling, didactisch zover voorloopt dat het in de huidige groep geheel geen uitdaging meer heeft, ook niet door het invoeren van compacten en verrijken, of wellicht door de samenstelling van de groep. Veelal heeft de (hoog)begaafde leerling dan ook weinig aansluiting binnen de klas. Een zorgvuldige overweging moet dan gemaakt worden of het verstandig is om de leerling te versnellen. Het versnellen zal in goed overleg en goed doordacht plaats vinden. Overleg over de juistheid van de beslissing met de ouders en de leerkracht van de ontvangende groep is van belang. Ook de wijze waarop een leerling wordt versneld is van belang. Het is mogelijk om een leerling in de huidige groep te laten en het vervolgens 2 groepen in 1 jaar te laten doen, de leerling kan naar de volgende groep gezet worden en daar de mogelijk gemiste stof inhalen. De beslissing is telkens afhankelijk van de situatie van de leerling en de mogelijkheden van de school. In de nieuwe groep is het van belang om direct weer met compacten en verrijken te beginnen, omdat de leerling anders al snel weer een voorsprong op kan bouwen.
