---
title: "Actueel"
---

Binnen de Subsidieregeling Excellentieprogramma Basisonderwijs van het ministerie van Onderwijs, Cultuur en Wetenschappen is er 5 miljoen euro beschikbaar gesteld voor initiatieven op het gebied van de verbetering van het onderwijs aan (hoog)begaafde leerlingen. Het uitgangspunt is om de excellente leerlingen meer uitdaging en ruimte te bieden binnen het huidige onderwijsbestel, zie ook www.cfi.nl.

Binnen dit excellentie programma liggen de prioriteiten bij:
- welke leerlingen op school het talent hebben om uitzonderlijke cognitieve prestaties te leveren (signalering en diagnostiek)
- het onderpresteren tegengaan bij taal en rekenen en andere vakken
- meehelpen met het bevorderen van een cultuur waarin excellente prestaties gewaardeerd worden. 

Schoolbesturen kunnen de aanvraag voor een subsidie in de periode van 1 januari tot uiterlijk 28 februari 2009 bij CFI indienen.

"De Begaafden Wijzer" wil met u meedenken en u ondersteunen bij het maken van projectplannen en het aanvragen van subsidie in het kader van deze regeling.

"De Begaafden Wijzer" kan zorg dragen voor een inventarisatie van de huidige situatie van het onderwijs aan (hoog)begaafde leerlingen bij scholen, via een gedigitaliseerde vorm van de checklist van het SLO(Stichting Leerplan Ontwikkeling).

Voor meer informatie: debegaafdenwijzer@upcmail.nl
